const MIN_IMAGE_DIMENSIONS_PX = 300;
const MAX_IMAGE_SIZE_MB = 5;

const NEW_STUDY_QUERY_KEY_PREFIX = 'NewStudy';

const MAX_SELECTED_DIAGNOSTICS = 1;

export {
  MIN_IMAGE_DIMENSIONS_PX,
  MAX_IMAGE_SIZE_MB,
  NEW_STUDY_QUERY_KEY_PREFIX,
  MAX_SELECTED_DIAGNOSTICS,
};
